setwd("/Users/Kelvin/Documents/Homework/Coursework/yr3sem1/STAT 331")
workdat <- read.table("senic.txt", header=T)
attach(workdat)
summary(lm(InfctRsk ~ Stay,workdat))
summary(lm(InfctRsk ~ Cultures,workdat))
summary(lm(InfctRsk ~ Age,workdat))
summary(lm(InfctRsk ~ Census,workdat))
summary(lm(InfctRsk ~ Beds,workdat))
summary(lm(InfctRsk ~ Cultures + Stay,workdat))
summary(lm(InfctRsk ~ Cultures + Age,workdat))
summary(lm(InfctRsk ~ Cultures + Census,workdat))
summary(lm(InfctRsk ~ Cultures + Beds,workdat))
summary(lm(InfctRsk ~ Cultures + Stay + Age,workdat))
summary(lm(InfctRsk ~ Cultures + Stay + Census,workdat))
summary(lm(InfctRsk ~ Cultures + Stay + Beds,workdat))
summary(lm(InfctRsk ~ Cultures + Stay + Beds + Age,workdat))
summary(lm(InfctRsk ~ Cultures + Stay + Beds + Census,workdat))
summary(lm(InfctRsk ~ Stay + Cultures + Age + Census + Beds,workdat))
summary(lm(InfctRsk ~ Stay + Cultures + Age + Census,workdat))
summary(lm(InfctRsk ~ Stay + Cultures + Census,workdat))